export enum Subjects {
  UserCreated = 'user.created',
  UserUpdated = 'user.updated',
  VerificationEmailSent = 'verification-email.sent',
  VerificationInitiated = 'verification.initiated',
  VerificationEmailConfirmed = 'verification-email.confirmed',
  VerificationAbandoned = 'verification.abandoned',
  VerificationDeleted = 'verification.deleted',
  AccountCreated = 'account.created',
  FusionTenantCreated = 'fusion-tenant.created',
  FusionApplicationCreated = 'fusion-application.created',
  MerchantOwnerCreated = 'merchant-owner.created',
  FusionUserCreated = 'fusion-user.created',
  PhoneVerificationOtpSent = 'verification-phone-otp.sent',
  PhoneVerificationOtpVerified = 'verification-phone-otp.verified',
  VerificationUpdated = 'verification.updated',
  ForgotPassword = 'forgot.password',
  ApiUserCreated = 'api-user.created',
  RoleCreated = 'role.created',
  RoleUpdated = 'role.updated',
  InviteCreated = 'invite.created',
}
